<?php $this->form->prepare(); ?>
<?php echo $this->form()->openTag($this->form); ?>

<?php $titolo = $this->form->get('titolo'); ?>
<?php $filePath = $this->form->get('filePath'); ?>
<?php $btnSubmit = $this->form->get('submit'); ?>
<?php $categoria = $this->form->get('select'); ?>

<div id="creation">
    <div class=row>
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <?php echo $this->formRow($titolo); ?>
        </div>
    </div>

    <br>


<div class=row>
    <div class="col-sm-2"></div>
    <div class="col-sm-4 text-center">
        <?php echo $this->formRow($filePath); ?>

    </div>
    <div class="col-sm-4 text-center">
        <?php echo $this->formRow($categoria); ?>
        </div>
    <br>

    <div class=row>
        <div class="col-sm-2"></div>
        <div class="col-sm-8 text-center">
            <?php echo $this->formRow($btnSubmit); ?>
        </div>
    </div>
</div>

<br>

<?php echo $this->form()->closeTag(); ?>






