<br>
<div class=row>
    <form class="form-inline">
        <div class="form-group col-sm-9 ">
            <h2>Lista categoria documenti</h2>
        </div>
        <div class="col-sm-3"></div>
    </form>
    <div class="col-sm-8">
        <?php if (!count($this->paginator)) : ?>

        <?php else : ?>
            <table class="table text-center">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Nome categoria</th>
                    <th class="text-center">Azioni</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->paginator as $category)  : ?>
                    <?php /** @var \Application\Entity\CategoryDocumenti $category */ ?>

                    <tr>
                        <td><b>
                                <?php echo $category->getId(); ?>
                            </b>
                        </td>
                        <td><b>
                                <?php echo $category->getNome(); ?>
                            </b>
                        </td>
                        <td><b>
                                <button class="btn btn-danger elimina"
                                        corrispondenza="<?php echo $category->getId(); ?>">Elimina
                                </button>
                            </b>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </div>


    <div class="col-sm-4">
        <?php echo $this->partial(
            'partial/category-form.phtml',
            [
                'form' => $this->form,
            ]
        );
        ?>
    </div>
</div>


<?php echo $this->paginationControl(
    $this->paginator,
    'sliding',
    'partial/paginator.phtml'
); ?>

<script>
    $('#category-creation-add-category').click(function () {
        $.post("categoryDocumento/save",
            {
                nome: $('#text-nome').val()
            },
            function (data) {
                location.reload();
            });
    });
    <?php /** @var \Application\Entity\CategoryDocumenti $category */ ?>

    $('.elimina').click(function () {
        $numero = $(this).attr("corrispondenza");
        $.post("categoryDocumento/delete",
            {
                id: $numero
            },
            function (data) {
                location.reload();
            });
    });
</script>
